# Generated by Django 2.1.7 on 2019-03-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='imo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Ship'),
        ),
    ]
